### ISSUE TITLE
wiki example in Readme

### ISSUE THREAD

**Issue by Seandebasti** [rene78/Wikidata-Extractor#5]
In the readme there was a map mentioned: https://en.wikivoyage.org/wiki/Talk:Prague#Wikidata_items_for_dynamic_map

1) Its a great idea. How is the map generated?
2) why just a few polygons?

Thanks

**Comment by rene78** [comment]
Hi @Seandebasti,

1. Maps on wiki pages are displayed with help of [Kartographer](https://www.mediawiki.org/wiki/Extension:Kartographer)
2. There is a bug within Kartographer. Used to work flawlessly.

Cheers
René
